# Generated by Django 4.2.7 on 2025-09-10 18:18

import apps.orders.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderqueue',
            options={'ordering': ['queue_position', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_custome_27c506_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_status_190611_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_deliver_cac897_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_created_6dbd10_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderhistory',
            name='order_histo_order_i_df15f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='order_item_order_i_08a5da_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='order_item_menu_it_d16a96_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='completed_at',
            new_name='paid_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='discount_amount',
            new_name='service_fee',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='confirmed_at',
            new_name='validated_at',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_order_n_f3ada5_idx',
            old_name='order_order_n_06f120_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='actual_prep_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_feedback',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_rating',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='estimated_prep_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='feedback_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='internal_notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prepared_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prepared_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ready_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='customizations',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='special_instructions',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='orderqueue',
            name='actual_start_time',
        ),
        migrations.RemoveField(
            model_name='orderqueue',
            name='estimated_start_time',
        ),
        migrations.RemoveField(
            model_name='orderqueue',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='orderqueue',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='ndjodongouhs@gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='Souleman G', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='office_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('wallet', 'Wallet'), ('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='+237 688 582 648', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=apps.orders.models.generate_order_number, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('CANCELLED', 'Cancelled'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status_from',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status_to',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderqueue',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderqueue',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='reorderitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['employee', 'created_at'], name='orders_orde_employe_532148_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='orderhistory',
            index=models.Index(fields=['changed_by', 'timestamp'], name='orders_orde_changed_96f2d2_idx'),
        ),
        migrations.AddIndex(
            model_name='orderqueue',
            index=models.Index(fields=['queue_position', 'created_at'], name='orders_orde_queue_p_f23d33_idx'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders_order',
        ),
        migrations.AlterModelTable(
            name='orderhistory',
            table='orders_orderhistory',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='orders_orderitem',
        ),
        migrations.AlterModelTable(
            name='orderqueue',
            table='orders_orderqueue',
        ),
        migrations.AlterModelTable(
            name='reorderitem',
            table='orders_reorderitem',
        ),
    ]
