# Generated by Django 4.2.7 on 2025-09-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_prep_time',
            field=models.DurationField(blank=True, help_text='Time taken to prepare the order', null=True),
        ),
    ]
