# Generated by Django 4.2.7 on 2025-09-09 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('completed_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('wallet_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('mtn_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('orange_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('unique_customers', models.PositiveIntegerField(default=0)),
                ('new_customers', models.PositiveIntegerField(default=0)),
                ('repeat_customers', models.PositiveIntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('average_prep_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('peak_hour', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Sales Report',
                'verbose_name_plural': 'Daily Sales Reports',
                'db_table': 'daily_sales_report',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('successful_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('average_prep_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('order_completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('customer_satisfaction', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('peak_concurrent_users', models.PositiveIntegerField(default=0)),
                ('system_uptime', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Analytics',
                'verbose_name_plural': 'System Analytics',
                'db_table': 'system_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReportSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('daily_sales', 'Daily Sales Report'), ('weekly_sales', 'Weekly Sales Report'), ('monthly_sales', 'Monthly Sales Report'), ('menu_performance', 'Menu Performance Report'), ('user_activity', 'User Activity Report'), ('payment_summary', 'Payment Summary Report'), ('inventory_report', 'Inventory Report'), ('custom', 'Custom Report')], max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipients', models.ManyToManyField(related_name='report_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Subscription',
                'verbose_name_plural': 'Report Subscriptions',
                'db_table': 'report_subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('orders_placed', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('session_duration', models.DurationField(blank=True, null=True)),
                ('pages_viewed', models.PositiveIntegerField(default=0)),
                ('favorite_items_added', models.PositiveIntegerField(default=0)),
                ('reviews_given', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Report',
                'verbose_name_plural': 'User Activity Reports',
                'db_table': 'user_activity_report',
                'ordering': ['-date', '-total_spent'],
                'indexes': [models.Index(fields=['date', 'orders_placed'], name='user_activi_date_7f683f_idx'), models.Index(fields=['date', 'total_spent'], name='user_activi_date_bf390d_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('daily_sales', 'Daily Sales Report'), ('weekly_sales', 'Weekly Sales Report'), ('monthly_sales', 'Monthly Sales Report'), ('menu_performance', 'Menu Performance Report'), ('user_activity', 'User Activity Report'), ('payment_summary', 'Payment Summary Report'), ('inventory_report', 'Inventory Report'), ('custom', 'Custom Report')], max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type'], name='report_report__a84470_idx'), models.Index(fields=['status'], name='report_status_74972f_idx'), models.Index(fields=['generated_by'], name='report_generat_5528c6_idx'), models.Index(fields=['created_at'], name='report_created_2a12c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuItemPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of views that resulted in orders', max_digits=5)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('popularity_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('revenue_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Performance',
                'verbose_name_plural': 'Menu Item Performance Reports',
                'db_table': 'menu_item_performance',
                'ordering': ['-date', '-revenue'],
                'indexes': [models.Index(fields=['date', 'revenue'], name='menu_item_p_date_aede94_idx'), models.Index(fields=['date', 'quantity_sold'], name='menu_item_p_date_4d324c_idx')],
                'unique_together': {('menu_item', 'date')},
            },
        ),
    ]
